library(shiny)
library(shinyWidgets)
library(vctrs)
library(ggplot2)
library(DT)
library(tm)
library(tidyverse)
library(stopwords)
library(formattable)
library(plotly)
source("readWords.R", local = TRUE)
source("wordTable.R", local = TRUE)
source("letterTable.R", local = TRUE)
